### ISSUE TITLE
Example 15: Wrong CPF CNPJ for proxy

### ISSUE THREAD

**Issue by EkkeErick** [Sensedia/massadedados#246]
Please update the CPF/CNPJ of the phone number "proxy": "+5561990010001" for "cpfCnpj":"11112222235".

There was an error on the sample data that we provided.

**Comment by fabricenunes** [comment]
Certo, será feita a alteração.

**Comment by fabricenunes** [comment]
Alterado o cpf nos cenários 15 e 16. Já está na main do repositório da Sensedia.
