### ISSUE TITLE
Dúvida QREs -Massa 16

### ISSUE THREAD

**Issue by EkkeErick** [Sensedia/massadedados#247]
Em consulta ao seguinte manual do PIX: https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/Anexo%20I%20-%20Padr%C3%B5es%20para%20Inicia%C3%A7%C3%A3o%20do%20PIX.pdf

Temos na pagina 14 para o QR code Estatico que o campo ID26/ID01 é mandatório e deveria ser igual a chave PIX. No exemplo apresentado não foi apresentado o ID 01. O QR code é realmente válido?

**Comment by fabricenunes** [comment]
Sim, o QR é válido, porém pode ter escapado algum campo na montagem da sequência. Será revisado campo a campo para garantia.

**Comment by fabricenunes** [comment]
O QRCode está montado conforme o documento de padrões do PIX versão 3.0: 
https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoI-PadroesparaIniciacaodoPIX-versao3.0.0.pdf 

Na página 25 tem um exemplo de como deve ser o QRcode dinâmico, o da massa foi montado com base neste exemplo.
O exemplo da massa está assim: 

000201
010211
26770014BR.GOV.BCB.PIX2528apicaixa/pix/qr/v2/+5561990010001
52040000
5303986
5406258.90
5802BR
5910JOAO SILVA
6014BELO HORIZONTE
62190503***
6304E412

**Comment by fabricenunes** [comment]
Revisado e alterado o QRcode.
