### ISSUE TITLE
Dúvida QRDn - Massa 15

### ISSUE THREAD

**Issue by EkkeErick** [Sensedia/massadedados#248]
Em consulta ao seguinte manual do PIX: https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/Anexo%20I%20-%20Padr%C3%B5es%20para%20Inicia%C3%A7%C3%A3o%20do%20PIX.pdf

Temos na pagina 19 para o QR code dinamico que o campo ID26/ID01 não deve ser inserido. Além disso os campos ID26/ID21-24 são mandatórios e deveriam ser iguais aos dados da conta do creditor. Também temos que o ID80/ID25 deveria ser o link da URL, que também não consta no exemplo.

 O QR code é realmente válido?

**Comment by fabricenunes** [comment]
Sim, ele é válido. Pode ter escapado alguma lógica ou regra, mas será revisado campo a campo para garantia e vermos estas dúvidas.

**Comment by fabricenunes** [comment]
Fizemos a revisão geral do código de QRCode e já está disponível na main do repositório da Sensedia. 

Utilizamos o Anexo I –Padrões versão 3.0 como base para construir os QRCodes. Na página 25 tem um exemplo de construção de QRDN que utilizamos de guia. 

Segue o código de QRcode da massa 16 quebrado em partes para melhor leitura:

000201
010211
2650
	0014br.gov.bcb.pix
	2528bx.com.br/pix/+5561990010001
52040000
5303986
5406258.90
5802BR
5910JOAO SILVA
6014BELO HORIZONTE
62070503***
6304EF11
