### ISSUE TITLE
Set Point of Initiation Method as Reusable - Massas 15 e 16

### ISSUE THREAD

**Issue by EkkeErick** [Sensedia/massadedados#249]
Como o QR Code será utilizado múltiplas vezes nos testes é importante manter claro o campo ID01 como reutilizável.

**Comment by fabricenunes** [comment]
Certo, foi colocado como única vez no QRDN por ser dinâmico e sua natureza ser para única utilização, mas será alterado para que os testes possam rodar múltiplas vezes.

**Comment by fabricenunes** [comment]
Pesquisei e não achei nenhuma restrição imposta além do 01 ser setado como 11 ou 12. Acredito que seja apenas aqui a valiação.
Realizei a alteração na massa para que possa reutilizar.
