### ISSUE TITLE
Accounts Link

### ISSUE THREAD

**Issue by RalphBragg** [Sensedia/massadedados#3]
F2_Contas/get-accounts-200-1.json

This is a collection, so it shouldn't have a SELF

**Comment by abenderd** [comment]
@RalphBragg According to the documentation, the SELF parameter is mandatory for the _links_ object, for this reason we leave an example of calling with the expected id for each one. Do you believe it is better to remove it even though it is mandatory?

**Comment by RalphBragg** [comment]
Nope - if you're going to use a mandatory on a collection then it's fine but it's not blocking.
