### ISSUE TITLE
Funds API - Campo data.fees.performanceFee.amount fora do regex esperado

### ISSUE THREAD

**Issue by ErickRaidiam** [Sensedia/massadedados#337]
Evidence on https://web.conformance.directory.openbankingbrasil.org.br/log-detail.html?log=RbxJZfM2orZ5zHC&public=true

**Comment by fabricenunes** [comment]
Em tratamento, assim que ajustarmos atualizo aqui,

**Comment by fabricenunes** [comment]
Solucionado
